import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Backend/Navigation/Sidebar";
import Navbar from "@/components/Backend/Navigation/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className="md:ml-64 min-h-screen bg-neutral-100 dark:bg-neutral-800 md:peer-[.collapsed]/sidebar:ml-[58px] transition-all">
          <Navbar />
          <div className="px-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
